package group.fly.hibernate.entities;

// default package
// Generated May 17, 2022, 10:11:26 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SpamUsers generated by hbm2java
 */
@Entity
@Table(name = "spam_users",  uniqueConstraints = @UniqueConstraint(columnNames = { "user_tele_id",
		"user_from_group_id" }))
public class SpamUsers implements java.io.Serializable {

	private Long userId;
	private String userNameTele;
	private String userPhone;
	private Integer userTeleId;
	private Integer active;
	private String contactFirstname;
	private String contactLastname;
	private Integer userFromGroupId;
	private Date createdAt;
	private Date updatedAt;
	private String accessHash;

	public SpamUsers() {
	}

	public SpamUsers(String userNameTele, String userPhone, Integer userTeleId, Integer active, String contactFirstname,
			String contactLastname, Integer userFromGroupId, Date createdAt, Date updatedAt, String accessHash) {
		this.userNameTele = userNameTele;
		this.userPhone = userPhone;
		this.userTeleId = userTeleId;
		this.active = active;
		this.contactFirstname = contactFirstname;
		this.contactLastname = contactLastname;
		this.userFromGroupId = userFromGroupId;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.accessHash = accessHash;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "user_name_tele")
	public String getUserNameTele() {
		return this.userNameTele;
	}

	public void setUserNameTele(String userNameTele) {
		this.userNameTele = userNameTele;
	}

	@Column(name = "user_phone")
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_tele_id")
	public Integer getUserTeleId() {
		return this.userTeleId;
	}

	public void setUserTeleId(Integer userTeleId) {
		this.userTeleId = userTeleId;
	}

	@Column(name = "active")
	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	@Column(name = "contact_firstname")
	public String getContactFirstname() {
		return this.contactFirstname;
	}

	public void setContactFirstname(String contactFirstname) {
		this.contactFirstname = contactFirstname;
	}

	@Column(name = "contact_lastname")
	public String getContactLastname() {
		return this.contactLastname;
	}

	public void setContactLastname(String contactLastname) {
		this.contactLastname = contactLastname;
	}

	@Column(name = "user_from_group_id")
	public Integer getUserFromGroupId() {
		return this.userFromGroupId;
	}

	public void setUserFromGroupId(Integer userFromGroupId) {
		this.userFromGroupId = userFromGroupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "access_hash")
	public String getAccessHash() {
		return this.accessHash;
	}

	public void setAccessHash(String accessHash) {
		this.accessHash = accessHash;
	}

}
