package group.fly.entities;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblInsuranceProviders generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_providers")
public class TblInsuranceProviders implements java.io.Serializable {

	private Long insurance_provider_id;
	private String insurance_code;
	private String insurance_name;
	private Integer active_stt;
	private String created_date;
	private String edited_date;

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "insurance_provider_id", unique = true, nullable = false)
	public Long getInsuranceProviderId() {
		return this.insurance_provider_id;
	}

	public void setInsuranceProviderId(Long insuranceProviderId) {
		this.insurance_provider_id = insuranceProviderId;
	}

	@Column(name = "insurance_code")
	public String getInsuranceCode() {
		return this.insurance_code;
	}

	public void setInsuranceCode(String insuranceCode) {
		this.insurance_code = insuranceCode;
	}

	@Column(name = "insurance_name")
	public String getInsuranceName() {
		return this.insurance_name;
	}

	public void setInsuranceName(String insuranceName) {
		this.insurance_name = insuranceName;
	}

	@Column(name = "active_stt")
	public Integer getActiveStt() {
		return this.active_stt;
	}

	public void setActiveStt(Integer activeStt) {
		this.active_stt = activeStt;
	}

}
