package group.fly.entities;

// default package
// Generated Jun 14, 2021, 12:09:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblInsuranceBanks generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_banks")
public class TblInsuranceBanks implements java.io.Serializable {

	private Integer mapping_id;
	private int insurance_provider_id;
	private String bank_code;
	private String acc_bank_name;
	private String acc_bank_no;
	private Integer active_stt;
	private Integer fix_fee;
	private Float fix_rate;
	private Integer bank_code_type;

	public TblInsuranceBanks() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mapping_id", unique = true, nullable = false)
	public Integer getMappingId() {
		return this.mapping_id;
	}

	public void setMappingId(Integer mappingId) {
		this.mapping_id = mappingId;
	}

	@Column(name = "insurance_provider_id", nullable = false)
	public int getInsuranceProviderId() {
		return this.insurance_provider_id;
	}

	public void setInsuranceProviderId(int insuranceProviderId) {
		this.insurance_provider_id = insuranceProviderId;
	}

	@Column(name = "bank_code", nullable = false, length = 50)
	public String getBankCode() {
		return this.bank_code;
	}

	public void setBankCode(String bankCode) {
		this.bank_code = bankCode;
	}

	@Column(name = "acc_bank_name", length = 200)
	public String getAccBankName() {
		return this.acc_bank_name;
	}

	public void setAccBankName(String accBankName) {
		this.acc_bank_name = accBankName;
	}

	@Column(name = "acc_bank_no", length = 100)
	public String getAccBankNo() {
		return this.acc_bank_no;
	}

	public void setAccBankNo(String accBankNo) {
		this.acc_bank_no = accBankNo;
	}

	@Column(name = "active_stt")
	public Integer getActiveStt() {
		return this.active_stt;
	}

	public void setActiveStt(Integer activeStt) {
		this.active_stt = activeStt;
	}

	@Column(name = "fix_fee")
	public Integer getFixFee() {
		return this.fix_fee;
	}

	public void setFixFee(Integer fixFee) {
		this.fix_fee = fixFee;
	}

	@Column(name = "fix_rate", precision = 12, scale = 0)
	public Float getFixRate() {
		return this.fix_rate;
	}

	public void setFixRate(Float fixRate) {
		this.fix_rate = fixRate;
	}

	@Column(name = "bank_code_type")
	public Integer getBankCodeType() {
		return this.bank_code_type;
	}

	public void setBankCodeType(Integer bankCodeType) {
		this.bank_code_type = bankCodeType;
	}

}
