package group.fly.transport.entities;
// default package

// Generated May 21, 2019 3:00:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TblMoneyTransferTransaction generated by hbm2java
 */

public class TblMoneyTransferTransaction implements java.io.Serializable {

	private String transId;
	private String referenceId;//Mã giao dịch
	private String requestId;
	private Date requestTime;
	private String partnerCode;
	private String bankNo;//Mã ngân hàng
	private String accNo;//Số tài khoản NHang
	private Boolean accType;//0:số tài khoản;1:số thể
	private String memo;//Mô tả giao dịch
	private String gwStatusResponse;
	private String imtStatusResponse;
	private Long status;
	private Date transTime;
	private Date createdAt;
	private Date updatedAt;
	private BigDecimal isUpdate;
	private Double requestAmount;
	private Double transferRealAmount;//Số tiền cần chuyển
	private Double transferFeeAmount;
	private Integer transferFeeType;
	private String accName;
	private String appId;
	private Boolean isSend;
	private String messageNo;
	private Date gwDateOfTransaction;
	private Long gwTimeOfTransaction;
	private Date updatedEndStatusAt;
	private Long previousStatus;
	private String branchNo;
	private BigDecimal scanSucces;
	private BigDecimal connectorId;
	private BigDecimal bankResponseStatus;//Trạng thái bank trả về
	private String bankDescription;//Mô tả bank trả về
	private String bankRequestId;
	private BigDecimal chanel;

	public TblMoneyTransferTransaction() {
	}

	public TblMoneyTransferTransaction(String transId, BigDecimal scanSucces) {
		this.transId = transId;
		this.scanSucces = scanSucces;
	}

	public TblMoneyTransferTransaction(String transId, String referenceId, String requestId, Date requestTime,
			String partnerCode, String bankNo, String accNo, Boolean accType, String memo, String gwStatusResponse,
			String imtStatusResponse, Long status, Date transTime, Date createdAt, Date updatedAt, BigDecimal isUpdate,
			Double requestAmount, Double transferRealAmount, Double transferFeeAmount, Integer transferFeeType,
			String accName, String appId, Boolean isSend, String messageNo, Date gwDateOfTransaction,
			Long gwTimeOfTransaction, Date updatedEndStatusAt, Long previousStatus, String branchNo,
			BigDecimal scanSucces, BigDecimal connectorId, BigDecimal bankResponseStatus, String bankDescription,
			String bankRequestId, BigDecimal chanel) {
		this.transId = transId;
		this.referenceId = referenceId;
		this.requestId = requestId;
		this.requestTime = requestTime;
		this.partnerCode = partnerCode;
		this.bankNo = bankNo;
		this.accNo = accNo;
		this.accType = accType;
		this.memo = memo;
		this.gwStatusResponse = gwStatusResponse;
		this.imtStatusResponse = imtStatusResponse;
		this.status = status;
		this.transTime = transTime;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.isUpdate = isUpdate;
		this.requestAmount = requestAmount;
		this.transferRealAmount = transferRealAmount;
		this.transferFeeAmount = transferFeeAmount;
		this.transferFeeType = transferFeeType;
		this.accName = accName;
		this.appId = appId;
		this.isSend = isSend;
		this.messageNo = messageNo;
		this.gwDateOfTransaction = gwDateOfTransaction;
		this.gwTimeOfTransaction = gwTimeOfTransaction;
		this.updatedEndStatusAt = updatedEndStatusAt;
		this.previousStatus = previousStatus;
		this.branchNo = branchNo;
		this.scanSucces = scanSucces;
		this.connectorId = connectorId;
		this.bankResponseStatus = bankResponseStatus;
		this.bankDescription = bankDescription;
		this.bankRequestId = bankRequestId;
		this.chanel = chanel;
	}

	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	public String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public Date getRequestTime() {
		return this.requestTime;
	}

	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	public String getPartnerCode() {
		return this.partnerCode;
	}

	public void setPartnerCode(String partnerCode) {
		this.partnerCode = partnerCode;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public String getAccNo() {
		return this.accNo;
	}

	public void setAccNo(String accNo) {
		this.accNo = accNo;
	}

	public Boolean getAccType() {
		return this.accType;
	}

	public void setAccType(Boolean accType) {
		this.accType = accType;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getGwStatusResponse() {
		return this.gwStatusResponse;
	}

	public void setGwStatusResponse(String gwStatusResponse) {
		this.gwStatusResponse = gwStatusResponse;
	}

	public String getImtStatusResponse() {
		return this.imtStatusResponse;
	}

	public void setImtStatusResponse(String imtStatusResponse) {
		this.imtStatusResponse = imtStatusResponse;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public Date getTransTime() {
		return this.transTime;
	}

	public void setTransTime(Date transTime) {
		this.transTime = transTime;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public BigDecimal getIsUpdate() {
		return this.isUpdate;
	}

	public void setIsUpdate(BigDecimal isUpdate) {
		this.isUpdate = isUpdate;
	}

	public Double getRequestAmount() {
		return this.requestAmount;
	}

	public void setRequestAmount(Double requestAmount) {
		this.requestAmount = requestAmount;
	}

	public Double getTransferRealAmount() {
		return this.transferRealAmount;
	}

	public void setTransferRealAmount(Double transferRealAmount) {
		this.transferRealAmount = transferRealAmount;
	}

	public Double getTransferFeeAmount() {
		return this.transferFeeAmount;
	}

	public void setTransferFeeAmount(Double transferFeeAmount) {
		this.transferFeeAmount = transferFeeAmount;
	}

	public Integer getTransferFeeType() {
		return this.transferFeeType;
	}

	public void setTransferFeeType(Integer transferFeeType) {
		this.transferFeeType = transferFeeType;
	}

	public String getAccName() {
		return this.accName;
	}

	public void setAccName(String accName) {
		this.accName = accName;
	}

	public String getAppId() {
		return this.appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public Boolean getIsSend() {
		return this.isSend;
	}

	public void setIsSend(Boolean isSend) {
		this.isSend = isSend;
	}

	public String getMessageNo() {
		return this.messageNo;
	}

	public void setMessageNo(String messageNo) {
		this.messageNo = messageNo;
	}

	public Date getGwDateOfTransaction() {
		return this.gwDateOfTransaction;
	}

	public void setGwDateOfTransaction(Date gwDateOfTransaction) {
		this.gwDateOfTransaction = gwDateOfTransaction;
	}

	public Long getGwTimeOfTransaction() {
		return this.gwTimeOfTransaction;
	}

	public void setGwTimeOfTransaction(Long gwTimeOfTransaction) {
		this.gwTimeOfTransaction = gwTimeOfTransaction;
	}

	public Date getUpdatedEndStatusAt() {
		return this.updatedEndStatusAt;
	}

	public void setUpdatedEndStatusAt(Date updatedEndStatusAt) {
		this.updatedEndStatusAt = updatedEndStatusAt;
	}

	public Long getPreviousStatus() {
		return this.previousStatus;
	}

	public void setPreviousStatus(Long previousStatus) {
		this.previousStatus = previousStatus;
	}

	public String getBranchNo() {
		return this.branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	public BigDecimal getScanSucces() {
		return this.scanSucces;
	}

	public void setScanSucces(BigDecimal scanSucces) {
		this.scanSucces = scanSucces;
	}

	public BigDecimal getConnectorId() {
		return this.connectorId;
	}

	public void setConnectorId(BigDecimal connectorId) {
		this.connectorId = connectorId;
	}

	public BigDecimal getBankResponseStatus() {
		return this.bankResponseStatus;
	}

	public void setBankResponseStatus(BigDecimal bankResponseStatus) {
		this.bankResponseStatus = bankResponseStatus;
	}

	public String getBankDescription() {
		return this.bankDescription;
	}

	public void setBankDescription(String bankDescription) {
		this.bankDescription = bankDescription;
	}

	public String getBankRequestId() {
		return this.bankRequestId;
	}

	public void setBankRequestId(String bankRequestId) {
		this.bankRequestId = bankRequestId;
	}

	public BigDecimal getChanel() {
		return this.chanel;
	}

	public void setChanel(BigDecimal chanel) {
		this.chanel = chanel;
	}

}
